name: Build & Release

on:
  push:
    tags:
      - "v*"
  workflow_dispatch: {}

jobs:
  build:
    name: Build
    uses: ./.github/workflows/build.yml

  release:
    name: Release
    uses: ./.github/workflows/release.yml
    needs: build
    permissions: write-all
